AC Test Fix - LRAC-9468 | master
liferay-qa/liferay-portal pull request #1135
Opened 2021-10-05 17:46 UTC by AfonsoHSantos

https://issues.liferay.com/browse/LRAC-9468 (fix)
https://testray.liferay.com/home/-/testray/case_results?tab=runs&testrayBuildId=1566603846 (run)
[afonsohsantos#30](https://github.com/AfonsoHSantos/liferay-portal/pull/30)

2021-10-05 17:46 UTC, liferay-continuous-integration commented
Please only forward necessary changes to Brian Chan during stabilization. Nonurgent changes should wait until the ongoing DXP 7.4 GA1 and Portal 7.4 GA4 release has been completed. For more details on the release timeline and status, see <a href="https://liferay.slack.com/archives/C03BTCQBQ">product-delivery</a>.

2021-10-05 17:46 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2021-10-05 17:47 UTC, AfonsoHSantos commented
ci:test:sf

2021-10-05 17:48 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-32.liferay.com/job/test-portal-source-format/564/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-32.liferay.com//userContent/jobs/test-portal-source-format/builds/564/jenkins-report.html">here</a>.</b></p>

2021-10-05 17:50 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/4333ea44cc32d5c6ccfe9f69e6342cb944648713">4333ea44cc32d5c6ccfe9f69e6342cb944648713</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/AfonsoHSantos/liferay-portal/tree/LRAC-9468">LRAC-9468</a><br/>Branch GIT ID: <a href="https://github.com/AfonsoHSantos/liferay-portal/commit/765430b83f64995610c39b22b63ff1c8b7db7437">765430b83f64995610c39b22b63ff1c8b7db7437</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-32.liferay.com/job/test-portal-source-format/564/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-source-format/builds/564/jenkins-report.html">here</a>.</h5></details></html>

2021-10-05 17:51 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-32.liferay.com/job/test-portal-source-format/564/">test-portal-source-format#564</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-source-format/builds/564/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-qa/liferay-portal/pull/1135">liferay-qa#1135</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1566606345">[master] ci:test:sf - AfonsoHSantos &gt; liferay-qa - PR#1135 - 2021-10-05[10:47:55]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-32.liferay.com/job/publish-testray-report/1834/">publish-testray-report#1834</a><br/></div></div>

2021-10-05 18:46 UTC, ViniLopes20 requested changes
Hi @AfonsoHSantos, I think you can change:

```
AssertTextEquals(
	locator1 = "ACSegments#NO_MEMBER_TITLE",
	value1 = "There are no items found.");
```
**to** 

`ACUtils.viewNoResultsMessage(noResultMessage = "There are no items found.");`

2021-10-06 13:18 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-26.liferay.com/job/test-portal-source-format/386/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-26.liferay.com//userContent/jobs/test-portal-source-format/builds/386/jenkins-report.html">here</a>.</b></p>

2021-10-06 13:21 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/1298299082e8efd43661a88c8cc2b74eccfea16e">1298299082e8efd43661a88c8cc2b74eccfea16e</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/AfonsoHSantos/liferay-portal/tree/LRAC-9468">LRAC-9468</a><br/>Branch GIT ID: <a href="https://github.com/AfonsoHSantos/liferay-portal/commit/b6b31f583e26e1a34034706e89f2bdddb094cc1b">b6b31f583e26e1a34034706e89f2bdddb094cc1b</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-26.liferay.com/job/test-portal-source-format/386/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-26.liferay.com/userContent/jobs/test-portal-source-format/builds/386/jenkins-report.html">here</a>.</h5></details></html>

2021-10-06 13:22 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-26.liferay.com/job/test-portal-source-format/386/">test-portal-source-format#386</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-26.liferay.com/userContent/jobs/test-portal-source-format/builds/386/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-qa/liferay-portal/pull/1135">liferay-qa#1135</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1566922697">[master] ci:test:sf - AfonsoHSantos &gt; liferay-qa - PR#1135 - 2021-10-06[06:18:31]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-26.liferay.com/job/publish-testray-report/1243/">publish-testray-report#1243</a><br/></div></div>

2021-10-06 17:41 UTC, ViniLopes20 approved these changes

2021-10-06 21:43 UTC, liferay-continuous-integration commented
Pull request has been successfully forwarded to https://github.com/brianchandotcom/liferay-portal/pull/108292
[Console](https://test-1-26.liferay.com/job/forward-pullrequest/70//consoleFull)

2021-10-06 21:43 UTC, closed without merging