LRAC-10032 Persona 1 UAT automation
liferay-qa/liferay-portal pull request #1409
Opened 2021-12-16 00:27 UTC by joshitagaki

https://issues.liferay.com/browse/LRAC-10032
@calvinctvo take a look and know what you think.
We can probably wait on merging this but wanted to get a template on how we might want to go about creating more personas

2021-12-16 00:27 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2021-12-16 19:21 UTC, alexcandidos commented
hey guys, what about creating a new dir to put our persona tests in?
For example: `portalweb/tests/enduser/analyticscloud/personas/UATGenerateData.testcase`

I don't know how many personas we'll have and maybe in the future, we can have a different/better organization. I see you guys added `UAT` at the beginning of the test case file name, so it is already a good way to differentiate this group from the other.

Just giving a suggestion ;)

2021-12-16 19:29 UTC, joshitagaki commented
@alexcandidos thanks for the suggestion! I agree, I think putting this into a new directory would be a good practice.

2022-03-09 13:13 UTC, r4ddek requested changes

2022-03-09 13:13 UTC, r4ddek commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/analyticscloud/persona/generators/BennyBrowserPersona.testcase
> +		Navigator.openURL(baseURL = "https://osbasahdxpserver73-ac-stagingdxps.lfr.cloud/");
I'll have Marcellus create a new instance for our persona tests and when that happens we'll have to update this address.

2025-02-04 23:34 UTC, closed without merging