LRAC-10248
liferay-qa/liferay-portal pull request #1582
Opened 2022-02-11 23:21 UTC by joshitagaki

https://issues.liferay.com/browse/LRAC-10248
Bug ticket: https://issues.liferay.com/browse/LRAC-10247
https://github.com/joshitagaki/liferay-portal/pull/38

2022-02-11 23:21 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2022-02-11 23:42 UTC, joshitagaki commented
ci:test:sf

2022-02-11 23:44 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-36.liferay.com/job/test-portal-source-format/301/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-36.liferay.com/userContent/jobs/test-portal-source-format/builds/301/jenkins-report.html">here</a>.</b></p>

2022-02-11 23:51 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-36.liferay.com/job/test-portal-source-format/301/">test-portal-source-format#301</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-36.liferay.com/userContent/jobs/test-portal-source-format/builds/301/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-qa/liferay-portal/pull/1582">liferay-qa#1582</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1610868576">[master] ci:test:sf - joshitagaki &gt; liferay-qa - PR#1582 - 2022-02-11[15:43:15]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-36.liferay.com/job/publish-testray-report/1218/">publish-testray-report#1218</a><br/></div></div>

2022-02-14 13:15 UTC, ViniLopes20 commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/analyticscloud/DeleteSegments.testcase
> +	@description = "Feature ID: Bug | Automation ID: LRAC-10247 | Test Summary: Deleting a static segment does not remove user in known individuals"
Hey @joshitagaki, I think the description property would be better this way so we know which bug the tests are based on:

`@description = "Bug: LRAC-10247 | Automation ID: LRAC-10247 | Test Summary: Deleting a static segment does not remove user in known individuals"`

2022-02-14 13:20 UTC, ViniLopes20 commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/analyticscloud/DeleteSegments.testcase
> +		var propertyName = ACDXPSettings.connectDXPtoAnalyticsCloud(siteName = "Site Name");
Hey @joshitagaki, you don't need to put a variable to receive the name of the property, the connection macro should no longer return the name of the property, inside the getAssignedPropertyName macro the variable is being declared as global, so we can use its value directly in the tests (I believe it was missing remove the return from the macro, I had made this change in the tests that were in the old and updated way, but I think there are still some. I'll open a ticket to adjust this, but could you fix that file if possible?):

**Before:**
```
var propertyName = ACDXPSettings.connectDXPtoAnalyticsCloud(siteName = "Site Name");


ACProperties.switchProperty(propertyName = "${propertyName}");
```

**Now:**
```
ACDXPSettings.connectDXPtoAnalyticsCloud(siteName = "Site Name");


ACProperties.switchProperty(propertyName = "${assignedPropertyName}");
```

2022-02-14 13:25 UTC, ViniLopes20 requested changes
Hey @joshitagaki, I will put more suggestions for you:

- Put tasks to explain what you are doing in some parts of the code

- I think that after verifying that the individual is in the list of known individuals you could put the test to create the segment again with that individual and in this way assure that it appears in the list to be added by the segment again after the deletion of the previous one

2022-02-14 16:23 UTC, joshitagaki commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/analyticscloud/DeleteSegments.testcase
> +		var propertyName = ACDXPSettings.connectDXPtoAnalyticsCloud(siteName = "Site Name");
Oh nice! I'll make those changes

2022-02-14 16:24 UTC, joshitagaki commented
Thanks for the suggestions @ViniLopes20!

2022-02-14 19:12 UTC, joshitagaki commented
ci:test:sf

2022-02-14 19:16 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/a2916ca536916c60abe8355bcfbdad491584d994">a2916ca536916c60abe8355bcfbdad491584d994</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/joshitagaki/liferay-portal/tree/LRAC-10248">LRAC-10248</a><br/>Branch GIT ID: <a href="https://github.com/joshitagaki/liferay-portal/commit/4e50ad4c1f89f6cf5a2242f399f69cf63b5cac88">4e50ad4c1f89f6cf5a2242f399f69cf63b5cac88</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-26.liferay.com/job/test-portal-source-format/1442/"><strike><strong>test-portal-source-format</strong></strike></a></li></ul></div><h5>For more details click <a href="https://test-1-26.liferay.com/userContent/jobs/test-portal-source-format/builds/1442/jenkins-report.html">here</a>.</h5><pre><code>     [java] java.lang.Exception: Found 1 formatting issues:
     [java] 1: ./portal-web/test/functional/com/liferay/portalweb/tests/enduser/analyticscloud/DeleteSegments.testcase expected:&lt;...aticSegment \{
     [java]     task[ ("Connect the DXP to AC") \{
     [java]       ACDXPSettings.connectDXPtoAnalyticsCloud(siteName = "Site Name");
     [java]     \}
     [java] 
     [java]     task ("Add a new user") \{
     [java]       JSONUser.addUser(
     [java]         userEmailAddress = "ac@liferay.com",
     [java]         userFirstName = "ac",
     [java]         userLastName = "ac",
     [java]         userScreenName = "ac");
     [java]     \}
     [java] 
     [java]     task ("Sync the Contact Data") \{
     [java]       ACDXPSettings.syncNewContactData();
     [java]     \}
     [java] 
     [java]     task ("Sign in as new user") \{
     [java]       User.logoutAndLoginPG(
     [java]         userLoginEmailAddress = "ac@liferay.com",
     [java]         userLoginFullName = "ac ac");
     [java]     \}
     [java] 
     [java]     task ("View the site page") \{
     [java]       ACUtils.navigateToSitePage(
     [java]         pageName = "AC Page",
     [java]         siteName = "Site Name");
     [java]     \}
     [java] 
     [java]     task ("Close sessions") \{
     [java]       ACUtils.closeAllSessionsAndWait();
     [java]     \}
     [java] 
     [java]     task ("Switch to new property in AC") \{
     [java]       ACUtils.launchAC();
     [java] 
     [java]       ACProperties.switchProperty(propertyName = "\$\{propertyName\}");
     [java]     \}
     [java] 
     [java]     task ("Go to Segments and add a new segment") \{
     [java]       ACNavigation.goToSegments();
     [java] 
     [java]       ACSegments.createStaticSegment();
     [java] 
     [java]       ACSegments.nameSegment(segmentName = "Static Segment Test");
     [java] 
     [java]       ACSegments.addStaticMember(tableMember = "ac ac");
     [java] 
     [java]       ACSegments.saveSegment();
     [java]     \}
     [java] 
     [java]     task ("Delete the segment via Segment List") \{
     [java]       ACNavigation.goToSegments();
     [java] 
     [java]       ACSegments.viewSegmentName(searchTerm = "Static Segment Test");
     [java] 
     [java]       ACSegments.deleteSegment(searchTerm = "Static Segment Test");
     [java] 
     [java]       ACSegments.viewDeletedSegmentName(searchTerm = "Static Segment Test");
     [java]     \}
     [java] 
     [java]     task ("Go to Individual &gt; Known Individuals") \{
     [java]       ACNavigation.goToIndividuals();
     [java] </code></pre></details></html>

2022-02-14 19:22 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-26.liferay.com/job/test-portal-source-format/1442/">test-portal-source-format#1442</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-26.liferay.com/userContent/jobs/test-portal-source-format/builds/1442/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-qa/liferay-portal/pull/1582">liferay-qa#1582</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1611317870">[master] ci:test:sf - joshitagaki &gt; liferay-qa - PR#1582 - 2022-02-14[11:13:00]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-26.liferay.com/job/publish-testray-report/5202/">publish-testray-report#5202</a><br/></div></div>

2022-02-14 19:24 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-26.liferay.com/job/test-portal-source-format/1442/">test-portal-source-format#1442</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-26.liferay.com/userContent/jobs/test-portal-source-format/builds/1442/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-qa/liferay-portal/pull/1582">liferay-qa#1582</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1611317870">[master] ci:test:sf - joshitagaki &gt; liferay-qa - PR#1582 - 2022-02-14[11:13:00]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-26.liferay.com/job/publish-testray-report/5203/">publish-testray-report#5203</a><br/></div></div>

2022-02-14 20:15 UTC, joshitagaki commented
ci:test:sf

2022-02-14 20:17 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-33.liferay.com/job/test-portal-source-format/845/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-33.liferay.com/userContent/jobs/test-portal-source-format/builds/845/jenkins-report.html">here</a>.</b></p>

2022-02-14 20:19 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/a2916ca536916c60abe8355bcfbdad491584d994">a2916ca536916c60abe8355bcfbdad491584d994</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/joshitagaki/liferay-portal/tree/LRAC-10248">LRAC-10248</a><br/>Branch GIT ID: <a href="https://github.com/joshitagaki/liferay-portal/commit/9c18de5ca89597d336f24fdc94eca24b835750f1">9c18de5ca89597d336f24fdc94eca24b835750f1</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-33.liferay.com/job/test-portal-source-format/845/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-33.liferay.com/userContent/jobs/test-portal-source-format/builds/845/jenkins-report.html">here</a>.</h5></details></html>

2022-02-14 20:21 UTC, ViniLopes20 approved these changes

2022-02-14 20:22 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-33.liferay.com/job/test-portal-source-format/845/">test-portal-source-format#845</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-33.liferay.com/userContent/jobs/test-portal-source-format/builds/845/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-qa/liferay-portal/pull/1582">liferay-qa#1582</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1611329931">[master] ci:test:sf - joshitagaki &gt; liferay-qa - PR#1582 - 2022-02-14[12:16:06]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-33.liferay.com/job/publish-testray-report/3025/">publish-testray-report#3025</a><br/></div></div>

2022-02-14 20:24 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-33.liferay.com/job/test-portal-source-format/845/">test-portal-source-format#845</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-33.liferay.com/userContent/jobs/test-portal-source-format/builds/845/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-qa/liferay-portal/pull/1582">liferay-qa#1582</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1611329931">[master] ci:test:sf - joshitagaki &gt; liferay-qa - PR#1582 - 2022-02-14[12:16:06]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-33.liferay.com/job/publish-testray-report/3026/">publish-testray-report#3026</a><br/></div></div>

2022-02-15 18:51 UTC, alexcandidos commented
Starting to review! 👨🏽‍💻

2022-02-15 19:01 UTC, alexcandidos commented
Thanks for the suggestions @ViniLopes20 !

Hi @joshitagaki , Thanks for working on it!

The code looks good to me!

I'm forwarding it.

2022-02-15 19:01 UTC, alexcandidos commented
ci:forward

2022-02-15 19:01 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**

The pull request will automatically be forwarded to the user `brianchandotcom` if the following test suites pass:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

2022-02-15 19:01 UTC, liferay-continuous-integration commented
Skipping previously passed test suites:
`ci:test:relevant`
`ci:test:sf`

2022-02-15 19:02 UTC, liferay-continuous-integration commented
All required test suite(s) passed.
Forwarding pull request to `brianchandotcom`.
[Console](https://test-1-9.liferay.com/job/forward-pullrequest/273//consoleFull)

2022-02-15 19:02 UTC, liferay-continuous-integration commented
Pull request has been successfully forwarded to https://github.com/brianchandotcom/liferay-portal/pull/113443
[Console](https://test-1-9.liferay.com/job/forward-pullrequest/273//consoleFull)

2022-02-15 19:02 UTC, closed without merging