LRAC-10696
liferay-qa/liferay-portal pull request #1655
Opened 2022-03-04 22:55 UTC by ViniLopes20

2022-03-04 22:55 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2022-03-04 22:58 UTC, ViniLopes20 commented
ci:test:sf

2022-03-04 23:04 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-37.liferay.com/job/test-portal-source-format/429/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/429/jenkins-report.html">here</a>.</b></p>

2022-03-04 23:05 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 8 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/eee48579e6866efb140feb1cb74810f130a6e88d">eee48579e6866efb140feb1cb74810f130a6e88d</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/ViniLopes20/liferay-portal/tree/LRAC-10696">LRAC-10696</a><br/>Branch GIT ID: <a href="https://github.com/ViniLopes20/liferay-portal/commit/f0769b87dba6d463e2da502bae2a88331489cacb">f0769b87dba6d463e2da502bae2a88331489cacb</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-37.liferay.com/job/test-portal-source-format/429/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/429/jenkins-report.html">here</a>.</h5></details></html>

2022-03-04 23:09 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-37.liferay.com/job/test-portal-source-format/429/">test-portal-source-format#429</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/429/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-qa/liferay-portal/pull/1655">liferay-qa#1655</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1627361401">[master] ci:test:sf - ViniLopes20 &gt; liferay-qa - PR#1655 - 2022-03-04[14:58:13]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-37.liferay.com/job/publish-testray-report/1793/">publish-testray-report#1793</a><br/></div></div>

2022-03-07 13:10 UTC, alexcandidos commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/analyticscloud/CustomEventsFilterBreakdown.testcase
> +				ACEventAnalysis.clickToAddFilterButton();
hi @ViniLopes20 , I would suggest renaming this task to:
`Add the filter to analysis and check if the filter provides autocomplete suggestions`

I'm just changing `provide` to `provides` and `auto complete` to `autocomplete`.

What do you think?

2022-03-07 13:22 UTC, alexcandidos commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/analyticscloud/CustomEventsFilterBreakdown.testcase
> +		var attributeName = "city";
hi @ViniLopes20 , I would suggest renaming this test to:

`CheckAutocompleteSuggestionsForAllConditions` 

Remember that idea of having a combination of the TestCaseFile#TestCaseName:

In this case, it will be:

`CustomEventsFilterBreakdown#CheckAutocompleteSuggestionsForAllConditions`

instead of:

`CustomEventsFilterBreakdown#CreateEventAnalysisFilterProvideAutoCompleteSuggestionsForAllCondition``

cc: @manuferreira

2022-03-07 13:24 UTC, alexcandidos requested changes
Hi @ViniLopes20 , Thanks for working on it!

The code looks good to me! I just left a few suggestions, could you please take a look?

2022-03-07 20:52 UTC, ViniLopes20 commented
ci:test:sf

2022-03-07 20:56 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-16.liferay.com/job/test-portal-source-format/5929/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-16.liferay.com/userContent/jobs/test-portal-source-format/builds/5929/jenkins-report.html">here</a>.</b></p>

2022-03-07 20:58 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/0de64eb6649bc87190fe93e0ea01d194e31e065e">0de64eb6649bc87190fe93e0ea01d194e31e065e</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/ViniLopes20/liferay-portal/tree/LRAC-10696">LRAC-10696</a><br/>Branch GIT ID: <a href="https://github.com/ViniLopes20/liferay-portal/commit/03549896221d2769b6eca760e2878ab71b5c3003">03549896221d2769b6eca760e2878ab71b5c3003</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-16.liferay.com/job/test-portal-source-format/5929/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-16.liferay.com/userContent/jobs/test-portal-source-format/builds/5929/jenkins-report.html">here</a>.</h5></details></html>

2022-03-10 13:18 UTC, alexcandidos approved these changes
Hi @ViniLopes20 , Thanks for working on it!

The code looks good to me!

I'm forwarding it.

2022-03-10 13:19 UTC, alexcandidos commented
ci:forward

2022-03-10 13:19 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**

The pull request will automatically be forwarded to the user `brianchandotcom` if the following test suites pass:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

2022-03-10 13:19 UTC, liferay-continuous-integration commented
Skipping previously passed test suites:
`ci:test:relevant`
`ci:test:sf`

2022-03-10 13:20 UTC, liferay-continuous-integration commented
All required test suite(s) passed.
Forwarding pull request to `brianchandotcom`.
[Console](https://test-1-35.liferay.com/job/forward-pullrequest/111//consoleFull)

2022-03-10 13:20 UTC, liferay-continuous-integration commented
Pull request has been successfully forwarded to https://github.com/brianchandotcom/liferay-portal/pull/114455
[Console](https://test-1-35.liferay.com/job/forward-pullrequest/111//consoleFull)

2022-03-10 13:20 UTC, closed without merging