LRAC-10809
liferay-qa/liferay-portal pull request #1720
Opened 2022-03-31 16:32 UTC by ViniLopes20

2022-03-31 16:32 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2022-03-31 16:34 UTC, ViniLopes20 commented
ci:test:sf

2022-03-31 16:38 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/bae3728abcb750c7a038d139af912fcabb40a25f">bae3728abcb750c7a038d139af912fcabb40a25f</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/ViniLopes20/liferay-portal/tree/LRAC-10809">LRAC-10809</a><br/>Branch GIT ID: <a href="https://github.com/ViniLopes20/liferay-portal/commit/93420201fb7720f946d854b04c3fc5d91ce534d4">93420201fb7720f946d854b04c3fc5d91ce534d4</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-25.liferay.com/job/test-portal-source-format/1676/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-source-format/builds/1676/jenkins-report.html">here</a>.</h5></details></html>

2022-03-31 16:40 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-25.liferay.com/job/test-portal-source-format/1676/">test-portal-source-format#1676</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-source-format/builds/1676/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-qa/liferay-portal/pull/1720">liferay-qa#1720</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1652466331">[master] ci:test:sf - ViniLopes20 &gt; liferay-qa - PR#1720 - 2022-03-31[09:34:25]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-25.liferay.com/job/publish-testray-report/6049/">publish-testray-report#6049</a><br/></div></div>

2022-04-04 16:07 UTC, joshitagaki approved these changes
LGTM!

2022-04-04 16:50 UTC, christianstokes requested changes
Hey @ViniLopes20 the code looks great!

It looks like there is a mistaken spelling "pageNmae" that affects a few different tests (not just this one). 😄 It should be "pageName" instead.

Do you mind adding a commit to fix all the instances of pageNmae? Then I think it can be submitted, it looks great. 👏 

![pageNmae](https://user-images.githubusercontent.com/5176704/161592676-287a2189-0e85-42b2-9db8-e2a2306233f3.png)

2022-04-04 16:50 UTC, christianstokes commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/analyticscloud/AssetsForms.testcase
> -				pageNmae = "AC Page - Site Name - ${siteName}");
pageNmae should be pageName

2022-04-04 16:56 UTC, ViniLopes20 commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/analyticscloud/AssetsForms.testcase
> -				pageNmae = "AC Page - Site Name - ${siteName}");
Ohhh ok, no problem. I will make this change, thanks for noticing this 😄

2022-04-04 19:24 UTC, ViniLopes20 commented
ci:forward

2022-04-04 19:24 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**

The pull request will automatically be forwarded to the user `brianchandotcom` if the following test suites pass:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

2022-04-04 19:24 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest(master)/2660/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/2660/jenkins-report.html">here</a>.</b></p>

2022-04-04 19:25 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-25.liferay.com/job/test-portal-source-format/1707/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-source-format/builds/1707/jenkins-report.html">here</a>.</b></p>

2022-04-04 19:27 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/c78fe654703598f841cf7923c4d19526187f1899">c78fe654703598f841cf7923c4d19526187f1899</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/ViniLopes20/liferay-portal/tree/LRAC-10809">LRAC-10809</a><br/>Branch GIT ID: <a href="https://github.com/ViniLopes20/liferay-portal/commit/8e41e461377853aa403d490abd1714b05f36b980">8e41e461377853aa403d490abd1714b05f36b980</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-25.liferay.com/job/test-portal-source-format/1707/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-source-format/builds/1707/jenkins-report.html">here</a>.</h5></details></html>

2022-04-04 19:27 UTC, liferay-continuous-integration commented
All required test suite(s) passed.
Forwarding pull request to `brianchandotcom`.
[Console](https://test-1-25.liferay.com/job/test-portal-source-format/1707//consoleFull)

2022-04-04 19:28 UTC, liferay-continuous-integration commented
Pull request has been successfully forwarded to https://github.com/brianchandotcom/liferay-portal/pull/115676
[Console](https://test-1-25.liferay.com/job/test-portal-source-format/1707//consoleFull)

2022-04-04 19:28 UTC, closed without merging

2022-04-04 19:29 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-25.liferay.com/job/test-portal-source-format/1707/">test-portal-source-format#1707</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-source-format/builds/1707/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-qa/liferay-portal/pull/1720">liferay-qa#1720</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1655044764">[master] ci:test:sf - ViniLopes20 &gt; liferay-qa - PR#1720 - 2022-04-04[12:24:18]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-25.liferay.com/job/publish-testray-report/6160/">publish-testray-report#6160</a><br/></div></div>

2022-04-04 19:30 UTC, ViniLopes20 commented
Hi team, Thanks for reviewing!

I'm forwarding it!

2022-04-04 19:31 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest(master)/2660/">test-portal-acceptance-pullrequest(master)#2660</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/2660/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-qa/liferay-portal/pull/1720">liferay-qa#1720</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1655047943">[master] ci:test:relevant - ViniLopes20 &gt; liferay-qa - PR#1720 - 2022-04-04[12:24:20]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-27.liferay.com/job/publish-testray-report/7226/">publish-testray-report#7226</a><br/></div></div>