LRAC-10829
liferay-qa/liferay-portal pull request #1723
Opened 2022-03-31 19:51 UTC by ViniLopes20

2022-03-31 19:51 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2022-03-31 19:51 UTC, ViniLopes20 commented
ci:test:sf

2022-03-31 19:53 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-11.liferay.com/job/test-portal-source-format/6263/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-11.liferay.com/userContent/jobs/test-portal-source-format/builds/6263/jenkins-report.html">here</a>.</b></p>

2022-03-31 19:56 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 5 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/de79f222419877b274f24d4949a887f662836243">de79f222419877b274f24d4949a887f662836243</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/ViniLopes20/liferay-portal/tree/LRAC-10829">LRAC-10829</a><br/>Branch GIT ID: <a href="https://github.com/ViniLopes20/liferay-portal/commit/00435527fc729929a7c071791e78cc74615d3112">00435527fc729929a7c071791e78cc74615d3112</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-11.liferay.com/job/test-portal-source-format/6263/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-11.liferay.com/userContent/jobs/test-portal-source-format/builds/6263/jenkins-report.html">here</a>.</h5></details></html>

2022-03-31 20:00 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-11.liferay.com/job/test-portal-source-format/6263/">test-portal-source-format#6263</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-11.liferay.com/userContent/jobs/test-portal-source-format/builds/6263/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-qa/liferay-portal/pull/1723">liferay-qa#1723</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1652581036">[master] ci:test:sf - ViniLopes20 &gt; liferay-qa - PR#1723 - 2022-03-31[12:52:14]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-11.liferay.com/job/publish-testray-report/2297/">publish-testray-report#2297</a><br/></div></div>

2022-04-01 12:15 UTC, manuferreira approved these changes
The code looks good to me Vini, very good looking `viewTimelineItem` macro :grin:

2022-04-04 16:26 UTC, christianstokes commented on portal-web/test/functional/com/liferay/portalweb/macros/analyticscloud/ACIndividualsDashboard.macro
> +				locator1 = "ACEventAnalysis#VIEW_ANALYSIS_INFORMATION_SPECIFC_ORDER");
Typo:

_SPECIFC_
should be
_SPECIFIC_

2022-04-04 16:29 UTC, christianstokes requested changes
@ViniLopes20 the macro looks great! There is one typo in the path locator: VIEW_ANALYSIS_INFORMATION_**SPECIFC**_ORDER.

According to my search, it's only used by this macro. Can you fix it? Thanks!

2022-04-04 16:37 UTC, ViniLopes20 commented on portal-web/test/functional/com/liferay/portalweb/macros/analyticscloud/ACIndividualsDashboard.macro
> +				locator1 = "ACEventAnalysis#VIEW_ANALYSIS_INFORMATION_SPECIFC_ORDER");
Good catch, Chris. Thanks 😄

2022-04-04 19:24 UTC, ViniLopes20 commented
ci:forward

2022-04-04 19:24 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**

The pull request will automatically be forwarded to the user `brianchandotcom` if the following test suites pass:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

2022-04-04 19:25 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest(master)/1454/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-34.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/1454/jenkins-report.html">here</a>.</b></p>

2022-04-04 19:26 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-25.liferay.com/job/test-portal-source-format/1708/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-source-format/builds/1708/jenkins-report.html">here</a>.</b></p>

2022-04-04 19:28 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/c78fe654703598f841cf7923c4d19526187f1899">c78fe654703598f841cf7923c4d19526187f1899</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/ViniLopes20/liferay-portal/tree/LRAC-10829">LRAC-10829</a><br/>Branch GIT ID: <a href="https://github.com/ViniLopes20/liferay-portal/commit/7bac08594ffa1e8a502db00a735fbeda17cd64d4">7bac08594ffa1e8a502db00a735fbeda17cd64d4</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-25.liferay.com/job/test-portal-source-format/1708/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-source-format/builds/1708/jenkins-report.html">here</a>.</h5></details></html>

2022-04-04 19:28 UTC, liferay-continuous-integration commented
All required test suite(s) passed.
Forwarding pull request to `brianchandotcom`.
[Console](https://test-1-25.liferay.com/job/test-portal-source-format/1708//consoleFull)

2022-04-04 19:29 UTC, liferay-continuous-integration commented
Pull request has been successfully forwarded to https://github.com/brianchandotcom/liferay-portal/pull/115677
[Console](https://test-1-25.liferay.com/job/test-portal-source-format/1708//consoleFull)

2022-04-04 19:29 UTC, closed without merging

2022-04-04 19:30 UTC, ViniLopes20 commented
Hi team, Thanks for reviewing!

I'm forwarding it!

2022-04-04 19:31 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest(master)/1454/">test-portal-acceptance-pullrequest(master)#1454</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-34.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/1454/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-qa/liferay-portal/pull/1723">liferay-qa#1723</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1655047939">[master] ci:test:relevant - ViniLopes20 &gt; liferay-qa - PR#1723 - 2022-04-04[12:24:37]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-34.liferay.com/job/publish-testray-report/4084/">publish-testray-report#4084</a><br/></div></div>

2022-04-04 19:31 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-25.liferay.com/job/test-portal-source-format/1708/">test-portal-source-format#1708</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-source-format/builds/1708/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-qa/liferay-portal/pull/1723">liferay-qa#1723</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1655047946">[master] ci:test:sf - ViniLopes20 &gt; liferay-qa - PR#1723 - 2022-04-04[12:24:35]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-25.liferay.com/job/publish-testray-report/6161/">publish-testray-report#6161</a><br/></div></div>