LRAC-10869
liferay-qa/liferay-portal pull request #1735
Opened 2022-04-05 23:36 UTC by ViniLopes20

2022-04-05 23:36 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2022-04-05 23:38 UTC, ViniLopes20 commented
ci:test:sf

2022-04-05 23:39 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-25.liferay.com/job/test-portal-source-format/1722/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-source-format/builds/1722/jenkins-report.html">here</a>.</b></p>

2022-04-05 23:41 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/82c31bf7f1d8e47e1cbfdd06eb12ae17eae79dd9">82c31bf7f1d8e47e1cbfdd06eb12ae17eae79dd9</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/ViniLopes20/liferay-portal/tree/LRAC-10869">LRAC-10869</a><br/>Branch GIT ID: <a href="https://github.com/ViniLopes20/liferay-portal/commit/0af26ca25e1a0bf37c465cc02ddaab9ccb2aa9ef">0af26ca25e1a0bf37c465cc02ddaab9ccb2aa9ef</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-25.liferay.com/job/test-portal-source-format/1722/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-source-format/builds/1722/jenkins-report.html">here</a>.</h5></details></html>

2022-04-05 23:43 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-25.liferay.com/job/test-portal-source-format/1722/">test-portal-source-format#1722</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-source-format/builds/1722/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-qa/liferay-portal/pull/1735">liferay-qa#1735</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1656190644">[master] ci:test:sf - ViniLopes20 &gt; liferay-qa - PR#1735 - 2022-04-05[16:38:45]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-25.liferay.com/job/publish-testray-report/6204/">publish-testray-report#6204</a><br/></div></div>

2022-04-06 00:05 UTC, joshitagaki approved these changes
Nice! LGTM

2022-04-06 15:58 UTC, manuferreira requested changes

2022-04-06 15:58 UTC, manuferreira commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/analyticscloud/EmptyState.testcase
> +	test CheckAllMessageWhenNoPropertyNoDataSource {
Hey Vini, maybe replace `CheckAllMessageWhenNoPropertyNoDataSource` with `CheckAllMessagesWhenNoPropertyNoDataSource` would be better?

2022-04-06 17:20 UTC, ViniLopes20 commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/analyticscloud/EmptyState.testcase
> +	test CheckAllMessageWhenNoPropertyNoDataSource {
Hey Manu, I think the best name is `CheckMessageWhenNoPropertyNoDataSource`, What do you think?

2022-04-06 17:25 UTC, manuferreira commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/analyticscloud/EmptyState.testcase
> +	test CheckAllMessageWhenNoPropertyNoDataSource {
Yes, even better.

2022-04-07 18:37 UTC, manuferreira approved these changes
LGTM, thanks Vini.

2022-04-07 23:48 UTC, ViniLopes20 commented
Hi team, Thanks for reviewing!

I'm forwarding it!

2022-04-07 23:49 UTC, ViniLopes20 commented
ci:forward

2022-04-07 23:49 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**

The pull request will automatically be forwarded to the user `brianchandotcom` if the following test suites pass:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

2022-04-07 23:49 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest(master)/2917/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-30.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/2917/jenkins-report.html">here</a>.</b></p>

2022-04-07 23:50 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-25.liferay.com/job/test-portal-source-format/1747/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-source-format/builds/1747/jenkins-report.html">here</a>.</b></p>

2022-04-07 23:52 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/d0af80528f382349ab73476476c6ca3e135b2c37">d0af80528f382349ab73476476c6ca3e135b2c37</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/ViniLopes20/liferay-portal/tree/LRAC-10869">LRAC-10869</a><br/>Branch GIT ID: <a href="https://github.com/ViniLopes20/liferay-portal/commit/74a30ac9c4469f571223e232a253ae3e09801886">74a30ac9c4469f571223e232a253ae3e09801886</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-25.liferay.com/job/test-portal-source-format/1747/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-source-format/builds/1747/jenkins-report.html">here</a>.</h5></details></html>

2022-04-07 23:52 UTC, liferay-continuous-integration commented
All required test suite(s) passed.
Forwarding pull request to `brianchandotcom`.
[Console](https://test-1-25.liferay.com/job/test-portal-source-format/1747//consoleFull)

2022-04-07 23:52 UTC, liferay-continuous-integration commented
All required test suite(s) passed.
Forwarding pull request to `brianchandotcom`.
[Console](https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest(master)/2917//consoleFull)

2022-04-07 23:53 UTC, liferay-continuous-integration commented
Pull request has been successfully forwarded to https://github.com/brianchandotcom/liferay-portal/pull/115865
[Console](https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest(master)/2917//consoleFull)

2022-04-07 23:53 UTC, closed without merging

2022-04-07 23:53 UTC, liferay-continuous-integration commented
Pull request has been successfully forwarded to https://github.com/brianchandotcom/liferay-portal/pull/115866
[Console](https://test-1-25.liferay.com/job/test-portal-source-format/1747//consoleFull)

2022-04-07 23:54 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-25.liferay.com/job/test-portal-source-format/1747/">test-portal-source-format#1747</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-source-format/builds/1747/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-qa/liferay-portal/pull/1735">liferay-qa#1735</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1658234530">[master] ci:test:sf - ViniLopes20 &gt; liferay-qa - PR#1735 - 2022-04-07[16:49:18]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-25.liferay.com/job/publish-testray-report/6300/">publish-testray-report#6300</a><br/></div></div>

2022-04-07 23:56 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest(master)/2917/">test-portal-acceptance-pullrequest(master)#2917</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-30.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/2917/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-qa/liferay-portal/pull/1735">liferay-qa#1735</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1658235076">[master] ci:test:relevant - ViniLopes20 &gt; liferay-qa - PR#1735 - 2022-04-07[16:49:18]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-30.liferay.com/job/publish-testray-report/8327/">publish-testray-report#8327</a><br/></div></div>