LPS-126264
liferay-qa/liferay-portal pull request #30
Opened 2021-01-27 03:23 UTC by alexcandidos

2021-01-27 03:23 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2021-01-27 22:38 UTC, reizero00 requested changes

2021-01-27 22:38 UTC, reizero00 commented on modules/apps/data-engine/data-engine-test/src/testFunctional/tests/wem/fields/SeparatorField.testcase
> +		Navigator.openURL();
@alexcandidos 

I don't think this step is needed. Can you have them remove it and retest? User.firstLoginPG should get it to the place we need and the product menu should be ready for use.

2021-01-28 06:22 UTC, brianwulbern commented on modules/apps/data-engine/data-engine-test/src/testFunctional/tests/wem/fields/SeparatorField.testcase
> +		Navigator.openURL();
In addition to that, keeping with convention, we'll want to make sure each macro that changes the context/url has a line break between it.

So instead of:
```
        TestCase.setUpPortalInstance();
        User.firstLoginPG();
```

It should be:
```
        TestCase.setUpPortalInstance();

        User.firstLoginPG();
```

2021-01-28 22:20 UTC, alexcandidos commented on modules/apps/data-engine/data-engine-test/src/testFunctional/tests/wem/fields/SeparatorField.testcase
> +		Navigator.openURL();
Hey @reizero00  and @brianwulbern, thanks for your inputs! It went unnoticed by my eyes.

2021-01-28 22:23 UTC, alexcandidos commented
PR is updated and ready to be reviewed again.

2021-01-29 06:41 UTC, Hanlf commented
reviewing...

2021-01-29 10:19 UTC, Hanlf commented
Hi @Odrakir1 ,

There are some rebase error, so I merged these commits into one.

cc/ @alexcandidos

2021-01-29 10:19 UTC, Hanlf commented
Pull sent here: david-gutierrez-mesa#75

2021-01-29 10:19 UTC, closed without merging