LRAC-8261
liferay-qa/liferay-portal pull request #655
Opened 2021-08-13 23:11 UTC by alanafergs

2021-08-13 23:20 UTC, ViniLopes20 commented
ci:test:sf

2021-08-13 23:20 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-26.liferay.com/job/test-portal-source-format/223/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-26.liferay.com//userContent/jobs/test-portal-source-format/builds/223/jenkins-report.html">here</a>.</b></p>

2021-08-13 23:22 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 2 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/e59a43db56193f21b9f5e1f17794d46bd4327574">e59a43db56193f21b9f5e1f17794d46bd4327574</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/alanafergs/liferay-portal/tree/LRAC-8261">LRAC-8261</a><br/>Branch GIT ID: <a href="https://github.com/alanafergs/liferay-portal/commit/284307f554643de7871ecd44edf9aff543475c7e">284307f554643de7871ecd44edf9aff543475c7e</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-26.liferay.com/job/test-portal-source-format/223/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-26.liferay.com/userContent/jobs/test-portal-source-format/builds/223/jenkins-report.html">here</a>.</h5></details></html>

2021-08-13 23:24 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-26.liferay.com/job/test-portal-source-format/223/">test-portal-source-format#223</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-26.liferay.com/userContent/jobs/test-portal-source-format/builds/223/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-qa/liferay-portal/pull/655">liferay-qa#655</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1553311173">[master] ci:test:sf - alanafergs &gt; liferay-qa - PR#655 - 2021-08-13[16:20:31]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-26.liferay.com/job/publish-testray-report/673/">publish-testray-report#673</a><br/></div></div>

2021-08-16 21:51 UTC, alexcandidos commented on portal-web/test/functional/com/liferay/portalweb/macros/analyticscloud/ACUtils.macro
> +
hi @alanafergs , could you please move this macro to `ACSites.macro`? Since you are testing Sites, it should be better located there.

Thanks!

2021-08-16 21:52 UTC, alexcandidos commented on portal-web/test/functional/com/liferay/portalweb/paths/analyticscloud/ACUtils.path
> +</tr>
hi @alanafergs , could you please move this path to `ACSites.path`? Since you are testing Sites, it should be better located there.

Thanks!

2021-08-16 22:50 UTC, alexcandidos requested changes
Hi @alanafergs , could you please take a look at my comments?

2021-08-16 22:55 UTC, ViniLopes20 commented on portal-web/test/functional/com/liferay/portalweb/macros/analyticscloud/ACUtils.macro
> +
Hi @alexcandidos, she put the macro in `ACUtils.macro` because this macro serves to assert in all AC titles

2021-08-16 22:56 UTC, ViniLopes20 commented on portal-web/test/functional/com/liferay/portalweb/macros/analyticscloud/ACUtils.macro
> +
How would something general use be better to stay in `ACUtils.macro` or not?

2021-08-16 23:00 UTC, alanafergs commented on portal-web/test/functional/com/liferay/portalweb/paths/analyticscloud/ACUtils.path
> +</tr>
Hi @alexcandidos, i put the macro in ACUtils.macro because this macro is for declaring in all AC titles.

2021-08-16 23:32 UTC, alexcandidos commented
I see @ViniLopes20  and @alanafergs , thanks for clarifying!

2021-08-16 23:32 UTC, alexcandidos commented
Hi @alanafergs , Thanks for working on it!

The code looks good to me!

I'm forwarding it.

2021-08-16 23:33 UTC, alexcandidos commented
ci:forward

2021-08-16 23:33 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**

The pull request will automatically be forwarded to the user `brianchandotcom` if the following test suites pass:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

2021-08-16 23:33 UTC, liferay-continuous-integration commented
Skipping previously passed test suites:
`ci:test:relevant`
`ci:test:sf`

2021-08-16 23:35 UTC, liferay-continuous-integration commented
All required test suite(s) passed.
Forwarding pull request to `brianchandotcom`.
[Console](https://test-1-21.liferay.com/job/forward-pullrequest/254//consoleFull)

2021-08-16 23:36 UTC, liferay-continuous-integration commented
Pull request has been successfully forwarded to https://github.com/brianchandotcom/liferay-portal/pull/105641
[Console](https://test-1-21.liferay.com/job/forward-pullrequest/254//consoleFull)

2021-08-16 23:36 UTC, closed without merging