LRAC-8403
liferay-qa/liferay-portal pull request #762
Opened 2021-08-23 20:31 UTC by andreefarias

2021-08-23 21:53 UTC, reizero00 commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/analyticscloud/AssetsDocumentsAndMedia.testcase
> +				Pause(locator1 = "5000");
Why is there an explicit pause here?

2021-08-23 22:10 UTC, reizero00 requested changes

2021-08-23 22:10 UTC, reizero00 commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/analyticscloud/AssetsDocumentsAndMedia.testcase
> +			for (var name : list "ac,ac2,ac3") {
For maintainability and searchability, I think it would be better to not use a for loop list and to instead declare variables individually.

2021-08-23 22:10 UTC, reizero00 commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/analyticscloud/AssetsDocumentsAndMedia.testcase
> +				Pause(locator1 = "5000");
Why is there an explicit pause here?
 
- [ ] Consider moving to an implicit wait

2021-08-23 22:10 UTC, reizero00 commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/analyticscloud/AssetsDocumentsAndMedia.testcase
> +			Pause(locator1 = "30000");
Every time we use `ACUtils.closeAllSessions();` do we always need to pause for 30 seconds? If so, then why don't we just put the wait in the macro and clean it up everywhere else? If not, then we can just leave it.

2021-08-23 22:10 UTC, reizero00 commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/analyticscloud/AssetsDocumentsAndMedia.testcase
> +			Pause(locator1 = "10000");
I'm asking on the #poshi channel to bring up the possibility of having a more efficient way to wait for a download to finish:
https://liferay.slack.com/archives/CD7939WBE/p1629756403082500

2021-08-23 22:47 UTC, ViniLopes20 commented
ci:test:sf

2021-08-23 22:48 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-32.liferay.com/job/test-portal-source-format/237/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-32.liferay.com//userContent/jobs/test-portal-source-format/builds/237/jenkins-report.html">here</a>.</b></p>

2021-08-23 22:49 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 2 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/c5b7941a23bc521170f168a04fd91638312b1e44">c5b7941a23bc521170f168a04fd91638312b1e44</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/andreefarias/liferay-portal/tree/LRAC-8403">LRAC-8403</a><br/>Branch GIT ID: <a href="https://github.com/andreefarias/liferay-portal/commit/99c751cf9ce199e2be5184a5b8ed3110aacfa339">99c751cf9ce199e2be5184a5b8ed3110aacfa339</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-32.liferay.com/job/test-portal-source-format/237/"><strike><strong>test-portal-source-format</strong></strike></a></li></ul></div><h5>For more details click <a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-source-format/builds/237/jenkins-report.html">here</a>.</h5><pre><code>     [java] java.lang.Exception: Found formatting issues:
     [java] At least one commit message is missing a reference to a required JIRA project: BLADE, CLDSVCS, COMMERCE, IDE, LHC, LOOP, LPS, LRAC, LRCI, LRDOCS, LRIS, LRQA, OAUTH2, POSHI, RELEASE, SYNC, TR. Please verify that the JIRA project keys are specifiedin ci.properties in the liferay-portal repository.
     [java] 	at com.liferay.source.formatter.util.JIRAUtil.validateJIRAProjectNames(JIRAUtil.java:71)
     [java] 	at com.liferay.source.formatter.SourceFormatter._validateCommitMessages(SourceFormatter.java:1217)
     [java] 	at com.liferay.source.formatter.SourceFormatter.format(SourceFormatter.java:330)
     [java] 	at com.liferay.source.formatter.SourceFormatter.main(SourceFormatter.java:287)
[stopwatch] [run.batch.test.action: 52.472 sec]
     [echo] The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/portal-impl/build.xml:572: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/portal-impl/build.xml:706: Java returned: 1
      [get] Getting: http://test-1-32/job/test-portal-source-format/237//consoleText
      [get] To: /opt/dev/projects/github/liferay-portal/20210823154933358.txt
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/20210823154933358.txt
  [typedef] Could not load definitions from resource org/apache/maven/artifact/ant/antlib.xml. It could not be found.
  [taskdef] Could not load definitions from resource org/jacoco/ant/antlib.xml. It could not be found.
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/null1178028788.properties

merge-test-results:
    [mkdir] Created dir: /opt/dev/projects/github/liferay-portal/test-results/src
[beanshell] Copying /opt/dev/projects/github/liferay-portal/portal-impl/test-results/TEST-JenkinsLogAssertTest.xml to /opt/dev/projects/github/liferay-portal/test-results/src/TEST-JenkinsLogAssertTest.xml
[junitreport] Processing /opt/dev/projects/github/liferay-portal/test-results/TESTS-TestSuites.xml to /tmp/null1525087237
[junitreport] Loading stylesheet jar:file:/opt/java/ant/lib/ant-junit.jar!/org/apache/tools/ant/taskdefs/optional/junit/xsl/junit-frames.xsl
[junitreport] Transform time: 179ms
[junitreport] Deleting: /tmp/null1525087237
     [echo] A report with all the test results can be found at test-results/html/index.html.
    [mkdir] Created dir: /opt/dev/projects/github/liferay-jenkins-ee/test-results</code></pre></details></html>

2021-08-23 22:50 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-32.liferay.com/job/test-portal-source-format/237/">test-portal-source-format#237</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-source-format/builds/237/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-qa/liferay-portal/pull/762">liferay-qa#762</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1555343302">[master] ci:test:sf - andreefarias &gt; liferay-qa - PR#762 - 2021-08-23[15:47:50]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-32.liferay.com/job/publish-testray-report/718/">publish-testray-report#718</a><br/></div></div>

2021-08-23 23:19 UTC, alexcandidos commented
hi @andreefarias , sf check is failing because one of your commits is missing the LRAC-id. Please fix it.
It is `Add comment from refector` and should be `LRAC-8403 Add comment from refactor`

Thanks!

2021-08-24 17:44 UTC, andreefarias commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/analyticscloud/AssetsDocumentsAndMedia.testcase
> +			for (var name : list "ac,ac2,ac3") {
In this case, makes sense declare variables individual, but I'm not sure if it makes sense for cases we have just one for loop. Thanks!

2021-08-24 17:58 UTC, andreefarias commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/analyticscloud/AssetsDocumentsAndMedia.testcase
> +			Pause(locator1 = "30000");
There are some cases that aren't necessary, for that reason I don't think it's a good idea.

2021-08-24 18:00 UTC, andreefarias commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/analyticscloud/AssetsDocumentsAndMedia.testcase
> +			Pause(locator1 = "10000");
Thanks!

2021-08-24 18:41 UTC, reizero00 commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/analyticscloud/AssetsDocumentsAndMedia.testcase
> +			Pause(locator1 = "30000");
Maybe we should create a copy of the macro with a pause 30 seconds.

Example:
1. Create a new macro `ACUtils.closeAllSessionsLong();`
2. When the underlying issue has been fixed on AC we can search and replace all `ACUtils.closeAllSessionsLong();` with `ACUtils.closeAllSessions();`
3. Proceed to delete `ACUtils.closeAllSessionsLong();` macro

2021-08-24 22:40 UTC, ViniLopes20 commented
ci:test:sf

2021-08-24 22:41 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-27.liferay.com/job/test-portal-source-format/1040/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-27.liferay.com//userContent/jobs/test-portal-source-format/builds/1040/jenkins-report.html">here</a>.</b></p>

2021-08-24 22:42 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 2 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/de6379116225b1d2c9aee14d0a37d20c8660b0cc">de6379116225b1d2c9aee14d0a37d20c8660b0cc</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/andreefarias/liferay-portal/tree/LRAC-8403">LRAC-8403</a><br/>Branch GIT ID: <a href="https://github.com/andreefarias/liferay-portal/commit/5efc0852f653081962e5ccb35c04c18e17075528">5efc0852f653081962e5ccb35c04c18e17075528</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-27.liferay.com/job/test-portal-source-format/1040/"><strike><strong>test-portal-source-format</strong></strike></a></li></ul></div><h5>For more details click <a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-source-format/builds/1040/jenkins-report.html">here</a>.</h5><pre><code>     [java] java.lang.Exception: Found 10 formatting issues:
     [java] 1: ./portal-web/test/functional/com/liferay/portalweb/tests/enduser/analyticscloud/KnownIndividualsProfileActivities.testcase expected:&lt;...llSessionsAndWait();[]
     [java] 
     [java] 		ACUtils.launchAC...&gt; but was:&lt;...llSessionsAndWait();[	]
     [java] 
     [java] 		ACUtils.launchAC...&gt;
     [java] 2: ./portal-web/test/functional/com/liferay/portalweb/tests/enduser/analyticscloud/SitesInterests.testcase expected:&lt;...llSessionsAndWait();[]
     [java] 
     [java] 			ACUtils.launchA...&gt; but was:&lt;...llSessionsAndWait();[	]
     [java] 
     [java] 			ACUtils.launchA...&gt;
     [java] 3: ./portal-web/test/functional/com/liferay/portalweb/tests/enduser/analyticscloud/SitesVisitorsDayAndTime.testcase expected:&lt;...llSessionsAndWait();[]
     [java] 		\}
     [java] 
     [java] 		task ("Switc...&gt; but was:&lt;...llSessionsAndWait();[	]
     [java] 		\}
     [java] 
     [java] 		task ("Switc...&gt;
     [java] 4: ./portal-web/test/functional/com/liferay/portalweb/tests/enduser/analyticscloud/KnownIndividualsProfileActivitiesList.testcase expected:&lt;...llSessionsAndWait();[]
     [java] 
     [java] 		ACUtils.launchAC...&gt; but was:&lt;...llSessionsAndWait();[	]
     [java] 
     [java] 		ACUtils.launchAC...&gt;
     [java] 5: ./portal-web/test/functional/com/liferay/portalweb/tests/enduser/analyticscloud/EditSegments.testcase expected:&lt;...tor1 = "5000");
     [java] 		\}
     [java] []
     [java] 		ACUtils.closeAllS...&gt; but was:&lt;...tor1 = "5000");
     [java] 		\}
     [java] [		]
     [java] 		ACUtils.closeAllS...&gt;
     [java] 6: ./portal-web/test/functional/com/liferay/portalweb/tests/enduser/analyticscloud/AssetsDocumentsAndMedia.testcase expected:&lt;...llSessionsAndWait();[]
     [java] 		\}
     [java] 
     [java] 		task ("Switc...&gt; but was:&lt;...llSessionsAndWait();[	]
     [java] 		\}
     [java] 
     [java] 		task ("Switc...&gt;
     [java] 7: ./portal-web/test/functional/com/liferay/portalweb/tests/enduser/analyticscloud/SitesSessionTechnology.testcase expected:&lt;...llSessionsAndWait();[]
     [java] 
     [java] 			ACUtils.launchA...&gt; but was:&lt;...llSessionsAndWait();[	]
     [java] 
     [java] 			ACUtils.launchA...&gt;
     [java] 8: ./portal-web/test/functional/com/liferay/portalweb/tests/enduser/analyticscloud/PageProfileVisitorBehavior.testcase expected:&lt;...llSessionsAndWait();[]
     [java] 		\}
     [java] 
     [java] 		task ("Switc...&gt; but was:&lt;...llSessionsAndWait();[	]
     [java] 		\}</code></pre></details></html>

2021-08-24 22:43 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-27.liferay.com/job/test-portal-source-format/1040/">test-portal-source-format#1040</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-source-format/builds/1040/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-qa/liferay-portal/pull/762">liferay-qa#762</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1555672511">[master] ci:test:sf - andreefarias &gt; liferay-qa - PR#762 - 2021-08-24[15:40:40]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-27.liferay.com/job/publish-testray-report/2511/">publish-testray-report#2511</a><br/></div></div>

2021-08-25 16:44 UTC, ViniLopes20 commented
ci:test:sf

2021-08-25 16:45 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-31.liferay.com/job/test-portal-source-format/53/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-31.liferay.com//userContent/jobs/test-portal-source-format/builds/53/jenkins-report.html">here</a>.</b></p>

2021-08-25 16:47 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 2 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/a5f3fe337ec76d6551d36d20d624a66cbde9a700">a5f3fe337ec76d6551d36d20d624a66cbde9a700</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/andreefarias/liferay-portal/tree/LRAC-8403">LRAC-8403</a><br/>Branch GIT ID: <a href="https://github.com/andreefarias/liferay-portal/commit/f3ba5b6026ea1020a281145dae0c05e08fb0342b">f3ba5b6026ea1020a281145dae0c05e08fb0342b</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-31.liferay.com/job/test-portal-source-format/53/"><strike><strong>test-portal-source-format</strong></strike></a></li></ul></div><h5>For more details click <a href="https://test-1-31.liferay.com/userContent/jobs/test-portal-source-format/builds/53/jenkins-report.html">here</a>.</h5><div><p>POSHI Validation Failure<pre><code>     [exec] 2 errors in POSHI
     [exec] 
     [exec] Invalid macro command AACUtils#closeAllSessionsAndWait
     [exec] /opt/dev/projects/github/liferay-portal/portal-web/test/functional/com/liferay/portalweb/tests/enduser/analyticscloud/SegmentsCreationWebBehavior.testcase:250
     [exec] 
     [exec] Invalid macro class AACUtils
     [exec] /opt/dev/projects/github/liferay-portal/portal-web/test/functional/com/liferay/portalweb/tests/enduser/analyticscloud/SegmentsCreationWebBehavior.testcase:250
     [exec] 
     [exec] 
     [exec] 
     [exec] 
     [exec] FAILURE: Build failed with an exception.
     [exec] 
     [exec] * What went wrong:
     [exec] Execution failed for task ':validatePoshi'.
     [exec] &gt; Process 'command '/opt/java/jdk1.8.0_121-x64/bin/java'' finished with non-zero exit value 1
     [exec] 
     [exec] * Try:
     [exec] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
     [exec] 
     [exec] * Get more help at https://help.gradle.org
     [exec] 
     [exec] BUILD FAILED</code></pre></p></div></details></html>

2021-08-25 16:51 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-31.liferay.com/job/test-portal-source-format/53/">test-portal-source-format#53</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-31.liferay.com/userContent/jobs/test-portal-source-format/builds/53/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-qa/liferay-portal/pull/762">liferay-qa#762</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1556045533">[master] ci:test:sf - andreefarias &gt; liferay-qa - PR#762 - 2021-08-25[09:45:16]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-31.liferay.com/job/publish-testray-report/110/">publish-testray-report#110</a><br/></div></div>

2021-08-25 23:19 UTC, closed without merging