AC Automated Test - LRAC 8835 | master
liferay-qa/liferay-portal pull request #832
Opened 2021-08-27 21:09 UTC by AfonsoHSantos

https://issues.liferay.com/browse/LRAC-8835

2021-08-27 23:44 UTC, ViniLopes20 commented on portal-web/test/functional/com/liferay/portalweb/macros/analyticscloud/ACDXPSettings.macro
> +		ACDXPSettings.goToInstanceSettingsAC();
@AfonsoHSantos, I think you can put this navigation in your test

2021-08-27 23:45 UTC, ViniLopes20 commented on portal-web/test/functional/com/liferay/portalweb/macros/analyticscloud/ACDXPSettings.macro
> +		ACDXPSettings.navToSyncedContactDataMenu();
@AfonsoHSantos, I think you can put this navigation in your test

2021-08-27 23:48 UTC, ViniLopes20 commented on portal-web/test/functional/com/liferay/portalweb/macros/analyticscloud/ACDXPSettings.macro
> +		ACDXPSettings.assertSuccessfulConnection();
Hi @AfonsoHSantos, I think you can use `ACDXPSettings.connectDXPtoAnalyticsCloud();` and after you go to sync contact and do the assert

2021-08-27 23:52 UTC, ViniLopes20 commented on portal-web/test/functional/com/liferay/portalweb/macros/analyticscloud/ACDXPSettings.macro
> +			locator1 = "ACDXPSettings#SYNC_ALL_CONTACTS_NUMBER");
Hi @AfonsoHSantos, I think you can go to sync contact make a assert in the number and after you create a new user and return to sync contact and make another assert in the number

2021-08-27 23:56 UTC, ViniLopes20 commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/analyticscloud/AnalyticsCloudConnectionTest.testcase
>  	test AssertLiferayDataSourceContactCountPreview {
**Steps to this test:**

- Connect DXP to Analytics Cloud with sync by organizations
- Go to sync contact > Check the number
- Create a user
- Go to sync contact > Make a sync contact again
- Check the number

2021-08-28 00:00 UTC, alexcandidos commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/analyticscloud/AnalyticsCloudConnectionTest.testcase
> +			ACDXPSettings.assertDXPContactCountPreview(numberContacts = "1");
hi @AfonsoHSantos , keep in mind to create macros more generic and reusable with some defined purpose (actions, navigation, asserts, etc), the macros should be like a library/method with actions that we can reuse in other tests, this macro is too restricted to the context of your test only.

2021-08-28 00:01 UTC, alexcandidos requested changes
hi @AfonsoHSantos , could you please review the suggestions and send a new PR? 

Thanks!

2021-08-28 00:03 UTC, closed without merging

2021-08-30 19:18 UTC, AfonsoHSantos commented
hi @alexcandidos @ViniLopes20 , resent on #845